# Generated by Django 2.2.27 on 2022-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220524_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
